### ISSUE TITLE
2/3 of the time everything is trippled

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga-website#54]
I would say about 2/3 of the time when I refresh the page I see 3 copies of every manga instead of one. After a few refreshes it goes to one, then refresh again and back to 3.

**Comment by db-2001** [comment]
I've put something in my pull request that should address this, hopefully

**Comment by yacob841** [comment]
Normally when I first access it’s tripled and never violently refreshing. I’ll try to gather some data on it. We will see if your fix worked though.

**Comment by yacob841** [comment]
> I've put something in my pull request that should address this, hopefully. But the multiple entries in the library is something that I only experience sometimes and even then never tripled, only doubled. I will say if you violently keep refreshing, it's not surprising that it triples sometimes.

How long do you think until this is included in the docker image? The triple thing is whatever but I really like the gui updates you've done and have been impatiently waiting lol

**Comment by C9Glax** [comment]
@yacob841 @db-2001 Semesterbreak just started, so about to fix some stuff...

**Comment by db-2001** [comment]
@yacob841 see if this new version of the website is working for you better.

**Comment by yacob841** [comment]
Does the docker container auto update from GitHub merge or does it have to be manually?

**Comment by C9Glax** [comment]
docker hub gets automatically updated on pushes to the gihub repo.
just run `docker compose pull && docker compose up -d`

**Comment by yacob841** [comment]
I tried a pull and up and still showing the old. Let me try something

**Comment by yacob841** [comment]
Ugh, rookie mistake, the old site was cached, had to clear the cache to get it working. So far I haven’t seen the triple show up anymore. I do however have another issue, I tried adding a manga and now my tranga-api is crashing within the first 30 seconds. I’m passing out now I will try to get you logs tomorrow morning, but a quick glimpse I didn’t see any information that would point to a crash.

**Comment by yacob841** [comment]
Never mind, I felt abusive saying there’s an issue and making you wait hours so I went digging lol. I think I found it, basically on system start there’s a ton of Adding Job to Queue followed by ```[02/27/2024 22:11:12.223]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-cmFua2Vyc3JldHVybnJlbWFrZTIwMjE= Manga: Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.223]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-b3ZlcmdlYXJlZDIwMTc= Manga: Publication Overgeared b3ZlcmdlYXJlZDIwMTc=
[02/27/2024 22:11:12.224]     Manganato | Copy cover Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.224]     Manganato | Cover exists Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.224]     Manganato | Retrieving chapter-info Chapter Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE= 4  Publication Ranker's Return (Remake) cmFua2Vyc3JldHVybnJlbWFrZTIwMjE=
[02/27/2024 22:11:12.630]     Manganato | Downloading Images for /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz
[02/27/2024 22:11:12.631]     Manganato | Downloading image 001/058
[02/27/2024 22:11:12.781]     Manganato | /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz 002/058 OK
[02/27/2024 22:11:12.781]     Manganato | Downloading image 002/058
[02/27/2024 22:11:12.781] HttpDownloadC | Waiting 0.9985997 seconds
[02/27/2024 22:11:13.806]     Manganato | /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz 003/058 OK
[02/27/2024 22:11:13.806]     Manganato | Downloading image 003/058
[02/27/2024 22:11:13.806] HttpDownloadC | Waiting 0.9991993 seconds
[02/27/2024 22:11:14.829]     Manganato | /Manga/Ranker's Return (Remake)/Ranker's Return (Remake) - Vol.0 Ch.4.cbz 004/058 OK
[02/27/2024 22:11:14.829]     Manganato | Downloading image 004/058
[02/27/2024 22:11:14.829] HttpDownloadC | Waiting 0.9993405 seconds
[02/27/2024 22:11:15.239] ChromiumDownl | Page loaded.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Tranga.MangaConnectors.Mangasee.ParseSinglePublicationFromHtml(HtmlDocument document, String publicationId) in /src/Tranga/MangaConnectors/Mangasee.cs:line 134
   at Tranga.MangaConnectors.Mangasee.GetMangaFromUrl(String url) in /src/Tranga/MangaConnectors/Mangasee.cs:line 123
   at Tranga.MangaConnectors.Mangasee.GetMangaFromId(String publicationId) in /src/Tranga/MangaConnectors/Mangasee.cs:line 113
   at Tranga.Jobs.UpdateMetadata.ExecuteReturnSubTasksInternal(JobBoss jobBoss) in /src/Tranga/Jobs/UpdateMetadata.cs:line 27
   at Tranga.Jobs.Job.ExecuteReturnSubTasks(JobBoss jobBoss) in /src/Tranga/Jobs/Job.cs:line 92
   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 248
   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74```

**Comment by C9Glax** [comment]
Okay closing and moving to seperate issue

**Comment by yacob841** [comment]
So it's happened a few times again now, I have never received triples since the update but now about 5-10% of the time I get doubles. Way less frequent and as I said, doubles instead of triples but it does happen.

**Comment by db-2001** [comment]
Hm, this is strange, could you post more details about your set up? What web browser you're using, any reverse proxy if any.
